USE [master]
GO
/****** Object:  Database [SistemaCafeSoluble]    Script Date: 1/12/2022 22:27:40 ******/
CREATE DATABASE [SistemaCafeSoluble]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SistemaCafeSoluble', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SistemaCafeSoluble.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SistemaCafeSoluble_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SistemaCafeSoluble_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [SistemaCafeSoluble] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SistemaCafeSoluble].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SistemaCafeSoluble] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SistemaCafeSoluble] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SistemaCafeSoluble] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SistemaCafeSoluble] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SistemaCafeSoluble] SET ARITHABORT OFF 
GO
ALTER DATABASE [SistemaCafeSoluble] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SistemaCafeSoluble] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SistemaCafeSoluble] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SistemaCafeSoluble] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SistemaCafeSoluble] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SistemaCafeSoluble] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SistemaCafeSoluble] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SistemaCafeSoluble] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SistemaCafeSoluble] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SistemaCafeSoluble] SET  ENABLE_BROKER 
GO
ALTER DATABASE [SistemaCafeSoluble] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SistemaCafeSoluble] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SistemaCafeSoluble] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SistemaCafeSoluble] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SistemaCafeSoluble] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SistemaCafeSoluble] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SistemaCafeSoluble] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SistemaCafeSoluble] SET RECOVERY FULL 
GO
ALTER DATABASE [SistemaCafeSoluble] SET  MULTI_USER 
GO
ALTER DATABASE [SistemaCafeSoluble] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SistemaCafeSoluble] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SistemaCafeSoluble] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SistemaCafeSoluble] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SistemaCafeSoluble] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SistemaCafeSoluble] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'SistemaCafeSoluble', N'ON'
GO
ALTER DATABASE [SistemaCafeSoluble] SET QUERY_STORE = OFF
GO
USE [SistemaCafeSoluble]
GO
/****** Object:  Schema [PRODUCTO]    Script Date: 1/12/2022 22:27:40 ******/
CREATE SCHEMA [PRODUCTO]
GO
/****** Object:  Schema [SEGURIDAD]    Script Date: 1/12/2022 22:27:40 ******/
CREATE SCHEMA [SEGURIDAD]
GO
/****** Object:  Table [PRODUCTO].[PRODUCTO]    Script Date: 1/12/2022 22:27:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PRODUCTO].[PRODUCTO](
	[IdProducto] [int] IDENTITY(1,1) NOT NULL,
	[CodigoProducto] [nvarchar](10) NOT NULL,
	[NombreProducto] [varchar](100) NOT NULL,
	[Stock] [int] NOT NULL,
	[Precio] [float] NOT NULL,
	[Descripcion] [varchar](300) NULL,
	[EstadoFila] [bit] NOT NULL,
	[FechaRegistro] [datetime] NOT NULL,
	[UsuarioRegistro] [varchar](50) NOT NULL,
	[FechaModificacion] [datetime] NULL,
	[UsuarioModificacion] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[IdProducto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SEGURIDAD].[ROL]    Script Date: 1/12/2022 22:27:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SEGURIDAD].[ROL](
	[IdRol] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
	[Descripcion] [varchar](100) NULL,
	[EstadoFila] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdRol] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SEGURIDAD].[USUARIO]    Script Date: 1/12/2022 22:27:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SEGURIDAD].[USUARIO](
	[IdUsuario] [int] IDENTITY(1,1) NOT NULL,
	[IdRol] [int] NOT NULL,
	[Usuario] [varchar](50) NOT NULL,
	[password_hash] [varbinary](max) NOT NULL,
	[password_salt] [varbinary](max) NOT NULL,
	[EstadoFila] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdUsuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET IDENTITY_INSERT [PRODUCTO].[PRODUCTO] ON 
GO
INSERT [PRODUCTO].[PRODUCTO] ([IdProducto], [CodigoProducto], [NombreProducto], [Stock], [Precio], [Descripcion], [EstadoFila], [FechaRegistro], [UsuarioRegistro], [FechaModificacion], [UsuarioModificacion]) VALUES (1, N'ABC_01', N'Computadora', 10, 36000, NULL, 1, CAST(N'2022-11-30T00:00:00.000' AS DateTime), N'Admin', CAST(N'2022-11-30T21:28:34.473' AS DateTime), N'Admin')
GO
INSERT [PRODUCTO].[PRODUCTO] ([IdProducto], [CodigoProducto], [NombreProducto], [Stock], [Precio], [Descripcion], [EstadoFila], [FechaRegistro], [UsuarioRegistro], [FechaModificacion], [UsuarioModificacion]) VALUES (3, N'MO_123', N'Mouse Inalambrico 2', 110, 120, N'', 1, CAST(N'2022-11-30T21:32:18.130' AS DateTime), N'francisco', CAST(N'2022-11-30T21:33:44.697' AS DateTime), N'Admin')
GO
SET IDENTITY_INSERT [PRODUCTO].[PRODUCTO] OFF
GO
SET IDENTITY_INSERT [SEGURIDAD].[ROL] ON 
GO
INSERT [SEGURIDAD].[ROL] ([IdRol], [Nombre], [Descripcion], [EstadoFila]) VALUES (1, N'Admin', N'Administrador', 1)
GO
SET IDENTITY_INSERT [SEGURIDAD].[ROL] OFF
GO
SET IDENTITY_INSERT [SEGURIDAD].[USUARIO] ON 
GO
INSERT [SEGURIDAD].[USUARIO] ([IdUsuario], [IdRol], [Usuario], [password_hash], [password_salt], [EstadoFila]) VALUES (1, 1, N'admin', 0x6A1778FADD12066AFE65D85FC7EE31415919C5D860E790A8F8352A6D292CD5495D34BB93848A2ECFE31D65DE56A382F3E1CA077A0E653339FF790A930C191C04, 0x55981F23726F4FDB60939DC1D6600BEE2ACB4568DD26AEA2325E4143CA64EFA2547AD4DD663434BCDDB40E565AC0D26D5104E25AF724DE464ACA9EE59558D7729CB659FB34FE4C2C094D12DA0271126BBF96BCB7583957A02AAC3B19CA008B4BB1B2D07DB8F41DFE18D506F6CD91B981A6726E44C073E6A97708BC47993A5CE3, 1)
GO
SET IDENTITY_INSERT [SEGURIDAD].[USUARIO] OFF
GO
ALTER TABLE [PRODUCTO].[PRODUCTO] ADD  DEFAULT ((1)) FOR [EstadoFila]
GO
ALTER TABLE [SEGURIDAD].[ROL] ADD  DEFAULT ((1)) FOR [EstadoFila]
GO
ALTER TABLE [SEGURIDAD].[USUARIO] ADD  DEFAULT ((1)) FOR [EstadoFila]
GO
ALTER TABLE [SEGURIDAD].[USUARIO]  WITH CHECK ADD FOREIGN KEY([IdRol])
REFERENCES [SEGURIDAD].[ROL] ([IdRol])
GO
USE [master]
GO
ALTER DATABASE [SistemaCafeSoluble] SET  READ_WRITE 
GO
